// <auto-generated />
namespace SDCTest.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatevalidatemodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevalidatemodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201611080254357_update-validate-models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
